### ISSUE TITLE
Helm repo add peripli is failing 

### ISSUE THREAD

**Issue by sanjay-dc** [Peripli/peripli.github.io#3]
Hi Team,

Helm repo add of peripli is failing with below error
`helm repo add peripli 'https://peripli.github.io'
Error: Looks like "https://peripli.github.io" is not a valid chart repository or cannot be reached: yaml: line 121: did not find expected key`

Looks like recent commit might have caused this issue, please address this issue

**Comment by alexwo** [comment]
Hi @sanjay-dc ,

Thanks for reporting,  should be fixed now.
please try again now.

**Comment by sanjay-dc** [comment]
Thanks @alexwo , issue is fixed
